version: '3.8'

name: "Insta-Telegram-Bot"

services:
  bot:
    build: .
    container_name: telegram_bot
    environment:
      - API_TOKEN = ${API_TOKEN}
      - INSTA_USERNAME = ${INSTA_USERNAME}
      - CHANNEL_ID = ${CHANNEL_ID}
    volumes:
      - .:/app
    restart: always